global:
  message: Welcome to MicroService World

logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoints:
    health:
      show-details: always
